### ISSUE TITLE
Saying "no" to the question "is this correct (y/n)? crashes the program after you pick the new class

### ISSUE THREAD

**Issue by TownsendSP** [MasonPrimrose/skillissue.py#1]

**Comment by TownsendSP** [comment]
```python
Choose a class:
wizard 1
priest 2
knight 3
rogue 4
bard 5
red mage 6
Selection: 1
human 1
elf 2
halfling 3
gnome 4
dwarf 5
Selection: 1
What is your name, brave adventurer? 🍕🍕
🍕🍕 the  human wizard
is this correct (y/n)? n
Choose a class:
wizard 1
priest 2
knight 3
rogue 4
bard 5
red mage 6
Selection: 1
human 1
elf 2
halfling 3
gnome 4
dwarf 5
Selection: 1
Traceback (most recent call last):
  File "/home/tgsp/rrat/skillissue.py/./RatKillingSim.py", line 2439, in <module>
    createpc()
  File "/home/tgsp/rrat/skillissue.py/./RatKillingSim.py", line 2262, in createpc
    pc.clss.spell = skills[pc.clss.spell-1]
IndexError: list index out of range
```
